sudo: false
script: bundle exec rake
before_script: ${PHANTOMJS:-phantomjs} --version
before_install:
   - mkdir travis-phantomjs2 travis-phantomjs21
   - wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -O $PWD/travis-phantomjs2/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
   - tar -xvf $PWD/travis-phantomjs2/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -C $PWD/travis-phantomjs2
   - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/phantomjs-2.1-linux-x86_64.tar.bz2
   - tar -xvf $PWD/phantomjs-2.1-linux-x86_64.tar.bz2 -C $PWD/travis-phantomjs21 --strip-components 2 phantomjs-2.1.1-linux-x86_64/bin/phantomjs
   - chmod +x $PWD/travis-phantomjs21/phantomjs
rvm:
  - 2.2.2
  - 2.1.6
  - 2.0.0
  - rbx-2
gemfile:
  - Gemfile
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

matrix:
  include:
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.1_9_3
    - rvm: jruby-19mode
      gemfile: gemfiles/Gemfile.1_9_3
    - rvm: 2.2.2
      gemfile: Gemfile
      env: PHANTOMJS=$PWD/travis-phantomjs2/phantomjs
    - rvm: 2.2.2
      gemfile: Gemfile
      env: PHANTOMJS=$PWD/travis-phantomjs21/phantomjs
    - rvm: 2.2.2
      gemfile: gemfiles/Gemfile.capybara_master
      env: PHANTOMJS=$PWD/travis-phantomjs2/phantomjs
    - rvm: 2.2.2
      gemfile: gemfiles/Gemfile.capybara_master
      env: PHANTOMJS=$PWD/travis-phantomjs21/phantomjs
  allow_failures:
    - gemfile: gemfiles/Gemfile.capybara_master
