dist: trusty
sudo: false
script: bundle exec rake
before_install:
   - nvm install 8.4.0
   - npm install ws
   - npm install git+https://github.com/GoogleChrome/puppeteer.git
   - node --version
   - yarn
cache:
  directories:
rvm:
  - 2.3.3
  - 2.2.2
  - 2.4.1
  - rbx-3
  - jruby-9.1.12.0
gemfile:
  - Gemfile
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - POLTERGEIST_TEST_HOST=poltergeist.test.com

addons:
  hosts:
    # Used to test custom host driver feature
    - poltergeist.test.com

matrix:
  include:
    - rvm: 2.4.1
      gemfile: gemfiles/Gemfile.capybara_master
  allow_failures:
    - gemfile: gemfiles/Gemfile.capybara_master
    - rvm: jruby-9.1.12.0
    - rvm: rbx-3
