before_script:
  - sudo ci/install_phantomjs
  - "export PATH=phantomjs/bin:$PATH"
  - phantomjs --version
script: bundle exec rake ci
rvm:
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - rbx-19mode
  - jruby-19mode
