dist: trusty
sudo: required
script: bundle exec rake
before_script: phantomjs --version
cache:
  directories:
    - $HOME/.phantomjs

rvm:
  - 2.3.1
  - 2.2.5
  - 2.1.6
  - 2.0.0
  - rubinius
gemfile:
  - gemfiles/Gemfile.phantomjs_2.1.1
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

matrix:
  include:
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.1_9_3
    - rvm: jruby-19mode
      gemfile: gemfiles/Gemfile.1_9_3
    - rvm: 2.2.2
      gemfile: Gemfile
    - rvm: 2.3.1
      gemfile: gemfiles/Gemfile.capybara_master
  allow_failures:
    - gemfile: gemfiles/Gemfile.capybara_master
