before_script:
  - "sudo ci/install_phantomjs"
  - "sudo apt-get install xvfb -y"
  - "Xvfb :0 &"
env: DISPLAY=:0
rvm:
  - 1.9.3
  - 1.9.2
  - 1.8.7
gemfile:
  - Gemfile
  - ci/Gemfile.capybara1-0
  - ci/Gemfile.capybara1-1
